databases:
  - name: piggybank
    databaseName: piggybank_33gs
    user: piggybank_33gs_user

services:
  - type: web
    name: piggycoin
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: piggybank
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false